# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import xenon_pb2 as xenon__pb2


class XenonJobsStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAdaptorStatuses = channel.unary_unary(
        '/xenon.XenonJobs/GetAdaptorStatuses',
        request_serializer=xenon__pb2.Empty.SerializeToString,
        response_deserializer=xenon__pb2.AdaptorStatuses.FromString,
        )


class XenonJobsServicer(object):

  def GetAdaptorStatuses(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_XenonJobsServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAdaptorStatuses': grpc.unary_unary_rpc_method_handler(
          servicer.GetAdaptorStatuses,
          request_deserializer=xenon__pb2.Empty.FromString,
          response_serializer=xenon__pb2.AdaptorStatuses.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'xenon.XenonJobs', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
