# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xenon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='xenon.proto',
  package='xenon',
  syntax='proto3',
  serialized_pb=_b('\n\x0bxenon.proto\x12\x05xenon\"\x07\n\x05\x45mpty\"/\n\x0eMAdaptorStatus\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07schemes\x18\x02 \x03(\t\":\n\x0f\x41\x64\x61ptorStatuses\x12\'\n\x08\x61\x64\x61ptors\x18\x01 \x03(\x0b\x32\x15.xenon.MAdaptorStatus2I\n\tXenonJobs\x12<\n\x12GetAdaptorStatuses\x12\x0c.xenon.Empty\x1a\x16.xenon.AdaptorStatuses\"\x00\x42\x30\n\x1cnl.esciencecenter.xenon.grpcB\x0eXenonJobsProtoP\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='xenon.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=29,
)


_MADAPTORSTATUS = _descriptor.Descriptor(
  name='MAdaptorStatus',
  full_name='xenon.MAdaptorStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='xenon.MAdaptorStatus.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='schemes', full_name='xenon.MAdaptorStatus.schemes', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=78,
)


_ADAPTORSTATUSES = _descriptor.Descriptor(
  name='AdaptorStatuses',
  full_name='xenon.AdaptorStatuses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='adaptors', full_name='xenon.AdaptorStatuses.adaptors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=138,
)

_ADAPTORSTATUSES.fields_by_name['adaptors'].message_type = _MADAPTORSTATUS
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['MAdaptorStatus'] = _MADAPTORSTATUS
DESCRIPTOR.message_types_by_name['AdaptorStatuses'] = _ADAPTORSTATUSES

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'xenon_pb2'
  # @@protoc_insertion_point(class_scope:xenon.Empty)
  ))
_sym_db.RegisterMessage(Empty)

MAdaptorStatus = _reflection.GeneratedProtocolMessageType('MAdaptorStatus', (_message.Message,), dict(
  DESCRIPTOR = _MADAPTORSTATUS,
  __module__ = 'xenon_pb2'
  # @@protoc_insertion_point(class_scope:xenon.MAdaptorStatus)
  ))
_sym_db.RegisterMessage(MAdaptorStatus)

AdaptorStatuses = _reflection.GeneratedProtocolMessageType('AdaptorStatuses', (_message.Message,), dict(
  DESCRIPTOR = _ADAPTORSTATUSES,
  __module__ = 'xenon_pb2'
  # @@protoc_insertion_point(class_scope:xenon.AdaptorStatuses)
  ))
_sym_db.RegisterMessage(AdaptorStatuses)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034nl.esciencecenter.xenon.grpcB\016XenonJobsProtoP\001'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class XenonJobsStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.GetAdaptorStatuses = channel.unary_unary(
          '/xenon.XenonJobs/GetAdaptorStatuses',
          request_serializer=Empty.SerializeToString,
          response_deserializer=AdaptorStatuses.FromString,
          )


  class XenonJobsServicer(object):

    def GetAdaptorStatuses(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_XenonJobsServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetAdaptorStatuses': grpc.unary_unary_rpc_method_handler(
            servicer.GetAdaptorStatuses,
            request_deserializer=Empty.FromString,
            response_serializer=AdaptorStatuses.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'xenon.XenonJobs', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaXenonJobsServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetAdaptorStatuses(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaXenonJobsStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def GetAdaptorStatuses(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    GetAdaptorStatuses.future = None


  def beta_create_XenonJobs_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('xenon.XenonJobs', 'GetAdaptorStatuses'): Empty.FromString,
    }
    response_serializers = {
      ('xenon.XenonJobs', 'GetAdaptorStatuses'): AdaptorStatuses.SerializeToString,
    }
    method_implementations = {
      ('xenon.XenonJobs', 'GetAdaptorStatuses'): face_utilities.unary_unary_inline(servicer.GetAdaptorStatuses),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_XenonJobs_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('xenon.XenonJobs', 'GetAdaptorStatuses'): Empty.SerializeToString,
    }
    response_deserializers = {
      ('xenon.XenonJobs', 'GetAdaptorStatuses'): AdaptorStatuses.FromString,
    }
    cardinalities = {
      'GetAdaptorStatuses': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'xenon.XenonJobs', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
